export const allowedCodesObject =  {
    "NEAR": true, "RNDR": true, "INJ": true, "GRT": true, "TAO": true, "THETA": true, "FET": true,
    "AKT": true, "AGIX": true, "ROSE": true, "AIOZ": true, "TFUEL": true, "ARKM": true, "GLM": true,
    "OCEAN": true, "IO": true, "TRAC": true, "PRIME": true, "TURBO": true, "ATH": true, "RSS3": true,
    "ABT": true, "FLUX": true, "PAAL": true, "NMT": true, "0x0": true, "AGI": true, "KDA": true,
    "POND": true, "RLC": true, "SURE": true, "NOS": true, "ZIG": true, "AI": true, "CQT": true,
    "NMR": true, "IQ": true, "ORAI": true, "LMWR": true, "OZO": true, "PHA": true, "PHB": true,
    "HOOK": true, "AITECH": true, "DKA": true, "CGPT": true, "NFP": true, "TOKEN": true, "FORT": true,
    "HASHAI": true, "CUDOS": true, "GPU": true, "TRIAS": true, "ALEPH": true, "CTXC": true, "VR": true,
    "DMTR": true, "DATA": true, "APRS": true, "DIA": true, "ALI": true, "AGRS": true, "LAT": true,
    "VAI": true, "SIDUS": true, "COMAI": true, "NUM": true, "BOTTO": true, "MDT": true, "SDAO": true,
    "VRA": true, "KEY": true, "VIRTUAL": true, "PALM": true, "GLQ": true, "HAI": true, "CERE": true,
    "DEAI": true, "UPP": true, "LIME": true, "HGPT": true, "PRQ": true, "VXV": true, "NTX": true,
    "VIDT": true, "VOLT": true, "DOCK": true, "DBC": true, "OORT": true, "MAN": true, "AIT": true,
    "DUEL": true, "OPTI": true, "GMRX": true, "LIKE": true, "FITFI": true, "BAD": true, "OFN": true,
    "DCK": true, "SPECTRE": true, "TRVL": true, "NCDT": true, "IMGNAI": true, "BCUT": true, "SNS": true,
    "SOUL": true, "NAVI": true, "OOKI": true, "TYPE": true, "BDP": true, "LMR": true, "XRT": true,
    "PIB": true, "AIPAD": true, "SWASH": true, "OMAX": true, "TADA": true, "LAMB": true, "GTAI": true,
    "EMC": true, "LITH": true, "LSS": true, "SENATE": true, "NETVR": true, "PRE": true, "BRG": true,
    "CGV": true, "MARSH": true, "ISP": true, "CHRP": true, "MOZ": true, "PBR": true, "DX": true,
    "UFI": true, "BCUBE": true, "MBD": true, "CTI": true, "EFX": true, "LUSH": true, "ROOBEE": true,
    "GNY": true, "MOOV": true, "GOC": true, "DERI": true, "WAM": true, "LBC": true, "UNO": true,
    "NEURA": true, "ABOND": true, "AXIS": true, "BIRD": true, "XMON": true, "IDNA": true, "AIMX": true,
    "AIRI": true, "TRV": true, "ALLIN": true, "MEFA": true, "CIRUS": true, "MMAI": true, "CATHEON": true,
    "AIBB": true, "TRAVA": true, "OCE": true, "ARCONA": true, "NEI": true, "OJA": true, "RAZE": true,
    "TRL": true, "YF-DAI": true, "CAIR": true, "UPI": true, "UBEX": true, "CNTM": true, "ASTO": true,
    "QUBIC": true, "GPT": true, "LAI": true, "OLAS": true, "DKS": true, "WORK": true, "THR": true,
    "XETA": true, "AIUS": true, "CORGIAI": true, "HEART": true, "GROK": true, "VIA": true, "GROW": true,
    "AIEPK": true, "RING": true, "FAKEAI": true, "BCAT": true, "Y8U": true, "METO": true, "AIN": true,
    "VRD": true, "HMT": true, "NEURAL": true, "MND": true, "enqAI": true, "AVTM": true, "TRACE": true,
    "TTM": true, "DDD": true, "LAVITA": true, "ZCN": true, "WNK": true, "ROKO": true, "VRX": true,
    "BTO": true, "BAI": true, "ASCN": true, "PAI": true, "GEMAI": true, "PALAI": true, "MOROS": true,
    "DHX": true, "ASTRA": true, "AIKEK": true, "TOR": true, "ORACLE": true, "2DAI": true, "CLBK": true,
    "CHAT": true, "AIMBOT": true, "NEURONI": true, "VUZZ": true, "BUILD": true, "VRSW": true, "RAVEN": true,
    "KWAI": true, "ACRIA": true, "WEBAI": true, "AION": true, "KAT": true, "AITK": true, "SAN": true,
    "DLT": true, "CND": true, "DNA": true, "CPC": true, "NTK": true, "SEELE": true, "HAVY": true,
    "EV": true, "AU": true, "IAI": true, "HERA": true, "USHI": true, "AIONE": true, "SAI": true, "LIZA": true,
    "GEMINI": true, "LNDRY": true, "BURNIFYAI": true, "MDX": true, "INSP": true, "AIMARKET": true, "PING": true,
    "TIE": true, "PRA": true, "DAT": true, "SPHTX": true, "CAT": true, "AIDOC": true, "INSTAR": true,
    "DATX": true, "LDC": true, "ADH": true, "MTC": true, "DAC": true, "QBIT": true, "FOAM": true,
    "LML": true, "ELAMA": true, "JAR": true, "CIX100": true, "SLV": true, "FAB": true, "MB": true,
    "REL": true, "ANW": true, "MBN": true, "AITRA": true, "UTU": true, "RIT20": true, "TESLF": true,
    "MAI": true, "MOVE": true, "QUAD": true, "BRAIN": true, "PEPES": true, "rushAI": true, "MIDAI": true,
    "KAE": true, "CIPHER": true, "DEFLECT": true, "DTEC": true, "WELLCHAIN": true, "ASI": true
} ;